enum {
	CALL_UNKNOWN_FUNCTION = 0,
	CALL_LOG_I,
	CALL_LOG_S,
	CALL_DISPLAY_VIDEO_MODE,
	CALL_DISPLAY_SPRITE,
	CALL_DISPLAY_SPRITE_ARRAY,
	CALL_DISPLAY_SYNC,
	CALL_INPUT_STATE,
	CALL_MEMSET
};